# Generated by Django 5.0.7 on 2024-07-16 20:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('asignatura', models.CharField(max_length=25)),
                ('fecha_ingreso', models.DateField()),
                ('hora_ingreso', models.TimeField()),
                ('profesor', models.CharField(max_length=20)),
                ('nro_espacio', models.CharField(choices=[('1RO', 'Primer Bloque'), ('2DO', 'Segundo Bloque'), ('3RO', 'Tercer Bloque'), ('4TO', 'Cuarto bloque')])),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=15)),
                ('modelo', models.CharField(max_length=25)),
                ('patente', models.CharField(max_length=6)),
                ('vin', models.CharField(max_length=17)),
                ('nivel_comb', models.CharField(choices=[('1/4', 'UN CUARTO'), ('1/2', 'MEDIO'), ('3/4', 'TRES CUARTOS'), ('1/1', 'LLENO')], default='1/4')),
                ('foto', models.ImageField(null=True, upload_to='vehicles/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('token_registro', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token_expiracion', models.DateTimeField(blank=True, null=True)),
                ('aceptar_terminos', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(related_name='usuarios', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='usuarios', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA_PROFESOR', 'Aprobada por Profesor'), ('RECHAZADA_PROFESOR', 'Rechazada por Profesor'), ('APROBADA_JEFE_CARRERA', 'Aprobada por Jefe de Carrera'), ('RECHAZADA_JEFE_CARRERA', 'Rechazada por Jefe de Carrera')], default='PENDIENTE', max_length=30)),
                ('mensaje', models.TextField(max_length=100, null=True)),
                ('detalle_solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.detallesolicitud')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='detallesolicitud',
            name='vehiculo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.vehiculo'),
        ),
    ]
