# Generated by Django 5.0.7 on 2024-07-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('GUARDIA', 'Guardia'), ('PROFESOR', 'Profesor'), ('SECRETARIO', 'Secretario'), ('JEFE_CARRERA', 'Jefe de Carrera')], default='ESTUDIANTE', max_length=20),
        ),
    ]
